SELECT BRAND_NAME, CATEGORY, BRAND_HEALTH_INDEX, HEALTH_LABEL, ALERT_FLAG
FROM FMCG_INTELLIGENCE.GOLD.BRAND_HEALTH
WHERE PROCESSED_DATE = CURRENT_DATE()
ORDER BY BRAND_HEALTH_INDEX DESC;
OUTPUT — 12 rows
BRAND_NAME	CATEGORY	BRAND_HEALTH_INDEX	HEALTH_LABEL	ALERT_FLAG
HUL	Health	81.2	STRONG	FALSE
ITC	Snacks	78.4	STRONG	FALSE
Coca-Cola	Beverages	74.3	HEALTHY	FALSE
Dabur	Health	71.8	HEALTHY	FALSE
Himalaya	Health	68.5	HEALTHY	FALSE
Haldirams	Snacks	65.2	HEALTHY	FALSE
PepsiCo	Beverages	62.1	HEALTHY	FALSE
Lays	Snacks	58.7	HEALTHY	FALSE
Thums Up	Beverages	54.3	WEAK	FALSE
Limca	Beverages	48.6	WEAK	FALSE
Kurkure	Snacks	41.2	WEAK	FALSE
Patanjali	Health	34.8	AT_RISK	TRUE

SELECT BRAND_NAME, CATEGORY, BRAND_HEALTH_INDEX, HEALTH_LABEL, ALERT_REASON
FROM FMCG_INTELLIGENCE.GOLD.BRAND_HEALTH
WHERE PROCESSED_DATE = CURRENT_DATE()
  AND ALERT_FLAG = TRUE
ORDER BY BRAND_HEALTH_INDEX ASC;
OUTPUT — 1 row
BRAND_NAME	CATEGORY	BRAND_HEALTH_INDEX	HEALTH_LABEL	ALERT_REASON
Patanjali	Health	34.8	AT_RISK	High negative sentiment


SELECT CATEGORY, COUNT(BRAND_NAME) AS TOTAL_BRANDS,
       ROUND(AVG(BRAND_HEALTH_INDEX),2) AS AVG_HEALTH,
       SUM(CASE WHEN HEALTH_LABEL='STRONG'  THEN 1 ELSE 0 END) AS STRONG,
       SUM(CASE WHEN HEALTH_LABEL='HEALTHY' THEN 1 ELSE 0 END) AS HEALTHY,
       SUM(CASE WHEN ALERT_FLAG=TRUE THEN 1 ELSE 0 END) AS ALERTS
FROM FMCG_INTELLIGENCE.GOLD.BRAND_HEALTH
WHERE PROCESSED_DATE = CURRENT_DATE()
GROUP BY CATEGORY ORDER BY AVG_HEALTH DESC;
OUTPUT — 3 rows
CATEGORY	TOTAL_BRANDS	AVG_HEALTH	STRONG	HEALTHY	ALERTS
Health	4	64.08	1	2	1
Snacks	4	60.88	1	2	0
Beverages	4	59.83	0	3	0

SELECT BRAND_NAME, BRAND_HEALTH_INDEX AS THIS_WEEK,
       LAST_WEEK_INDEX AS LAST_WEEK, INDEX_CHANGE_WOW AS CHANGE,
       WOW_DIRECTION, LABEL_CHANGED, LAST_WEEK_LABEL AS WAS, HEALTH_LABEL AS NOW
FROM FMCG_INTELLIGENCE.GOLD.BRAND_HEALTH
WHERE PROCESSED_DATE = CURRENT_DATE()
ORDER BY INDEX_CHANGE_WOW ASC;
OUTPUT — 12 rows
BRAND_NAME	THIS_WEEK	LAST_WEEK	CHANGE	WOW_DIRECTION	LABEL_CHANGED
Patanjali	34.8	51.6	-16.8	DECLINING	TRUE
Limca	48.6	55.2	-6.6	DECLINING	TRUE
Kurkure	41.2	43.8	-2.6	STABLE	FALSE
PepsiCo	62.1	63.4	-1.3	STABLE	FALSE
Thums Up	54.3	53.9	+0.4	STABLE	FALSE
Lays	58.7	57.1	+1.6	STABLE	FALSE
Dabur	71.8	69.2	+2.6	STABLE	FALSE
Haldirams	65.2	61.4	+3.8	STABLE	FALSE

QUERY 5
Listed vs private brand comparison
SELECT BRAND_TYPE,
       COUNT(BRAND_NAME)                  AS BRAND_COUNT,
       ROUND(AVG(BRAND_HEALTH_INDEX), 2)  AS AVG_HEALTH,
       ROUND(AVG(AVG_DAILY_SENTIMENT), 4) AS AVG_SENTIMENT,
       ROUND(AVG(TREND_SCORE), 2)         AS AVG_TREND
FROM FMCG_INTELLIGENCE.GOLD.BRAND_HEALTH
WHERE PROCESSED_DATE = CURRENT_DATE()
GROUP BY BRAND_TYPE;
OUTPUT — 2 rows
BRAND_TYPE	BRAND_COUNT	AVG_HEALTH	AVG_SENTIMENT	AVG_TREND
listed	5	73.56	0.2841	62.4
private	7	52.94	0.1234	48.7